### ISSUE TITLE
Exercise 22: Update Approuter version

### ISSUE THREAD

**Issue by nenaraab** [SAP/cloud-bulletinboard-ads#18]
- Update version of approuter to `6.1.0`
- in `.npmrc`
```
package-lock=true
@sap:registry=https://npm.sap.com
```
- Remove `Node_modules` from `.cfignore`

### Further References:
- https://docs.cloudfoundry.org/buildpacks/node/index.html#vendoring

**Comment by frnksgr** [comment]
* If the version of approuter is updated, the rest of the turorial has to be checked, if it need to be adapted due to changes in approuter.
* the point about package-lock and node_modules (not Node_modules) not in .cfignore is about vendoring your application on CF in order to provide strictly reproducible deployments. in the tutorial should be either a reference to vendoring or at least be mentioned that this is not a solution to be used poroductively.

**Comment by nenaraab** [comment]
Solution 22 updated to latest approuter version
