### ISSUE TITLE
Exercise 6 / 22 / 26: Remove deprecated attributes from Manifest

### ISSUE THREAD

**Issue by nenaraab** [SAP/cloud-bulletinboard-ads#19]
- remove `host key`
- buildpack: don't refer github version #13 
- remove timeout

### Reference
- https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html

**Comment by frnksgr** [comment]
* You cannot just remove host. the host key is marked deprecated for CF manifests. AFAIK the usage of host might need to be replaced by routes.
* Concerning buildpack references in CF manifests. There a several ways to do this. There should be clear guidance in such tutorials, how to do it best in the context of productive SAP solutions on that platform. Most likely there have been technical reasons to reference a buildpack from github. If so, this should be mentioned (which it isn't).

Due to CF still evolving and changing over time, we need tutorials/documents that are continuously aligned with those changes.
